# Generated by Django 5.1.1 on 2024-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('document', models.CharField(max_length=16)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=128)),
                ('birthDate', models.DateField()),
                ('rol', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
    ]
