# Generated by Django 5.1.1 on 2024-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastName',
            field=models.CharField(max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
