# Generated by Django 5.1.1 on 2024-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_firstname_alter_person_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=models.DateField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.CharField(max_length=16, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(max_length=16, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rol',
            field=models.CharField(max_length=32, verbose_name='Rol'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='people',
        ),
    ]
