# Generated by Django 4.2.16 on 2024-10-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_birthdate_alter_person_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
