# Generated by Django 5.1.1 on 2024-10-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('people', '0002_alter_person_firstname_alter_person_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(db_column='teacherId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
