# Generated by Django 5.1.1 on 2024-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Course_Student',
                'verbose_name_plural': 'Courses Students',
                'db_table': 'courses_students',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='maxCapacity',
            field=models.IntegerField(verbose_name='Max Capacity'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
