# Generated by Django 5.1.1 on 2024-10-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_student_alter_course_maxcapacity_and_more'),
        ('people', '0003_alter_person_birthdate_alter_person_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_student',
            name='course',
            field=models.ForeignKey(db_column='courseId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='course_student',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course_student',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course_student',
            name='state',
            field=models.CharField(choices=[('0', 'Inscrito'), ('1', 'Completado'), ('2', 'Retirado'), ('3', 'Pendiente'), ('4', 'En Espera'), ('5', 'Aprobado'), ('6', 'Reprobado'), ('7', 'Transferido')], default='0', max_length=24),
        ),
        migrations.AddField(
            model_name='course_student',
            name='student',
            field=models.ForeignKey(db_column='studentId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Student'),
        ),
    ]
