# Generated by Django 5.1.1 on 2024-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_student_course_course_student_enddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_student',
            options={'verbose_name': 'Course Student', 'verbose_name_plural': 'Courses Students'},
        ),
        migrations.AlterField(
            model_name='course_student',
            name='state',
            field=models.CharField(choices=[(0, 'Inscrito'), (1, 'Completado'), (2, 'Retirado'), (3, 'Pendiente'), (4, 'En Espera'), (5, 'Aprobado'), (6, 'Reprobado'), (7, 'Transferido')], default=0, max_length=24),
        ),
    ]
