# Generated by Django 5.1.1 on 2024-10-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_student',
            name='state',
            field=models.IntegerField(choices=[(0, 'Inscrito'), (1, 'Completado'), (2, 'Retirado'), (3, 'Pendiente'), (4, 'En Espera'), (5, 'Aprobado'), (6, 'Reprobado'), (7, 'Transferido')], default=0),
        ),
    ]
