# Generated by Django 4.2.16 on 2024-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
