# Generated by Django 4.2.16 on 2024-10-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_isactive_alter_course_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_student',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
