# Generated by Django 5.1.1 on 2024-10-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_alter_person_birthdate_alter_person_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16, verbose_name='State')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('student', models.ForeignKey(db_column='studentId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollements',
            },
        ),
    ]
