# Generated by Django 5.1.1 on 2024-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='state',
            field=models.IntegerField(choices=[(0, 'Inscrito'), (1, 'Completado'), (2, 'Retirado'), (3, 'Pendiente'), (4, 'En Espera'), (5, 'Aprobado'), (6, 'Reprobado'), (7, 'Transferido')], default=0, verbose_name='State'),
        ),
    ]
