# Generated by Django 4.2.16 on 2024-10-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_student_isactive'),
        ('enrollments', '0002_alter_enrollment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='studentCourse',
            field=models.ForeignKey(db_column='studentId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course_student', verbose_name='Student'),
        ),
    ]
