# Generated by Django 4.2.16 on 2024-10-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_enrollment_student_enrollment_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
