# Generated by Django 5.1.1 on 2024-10-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('people', '0003_alter_person_birthdate_alter_person_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Student'),
        ),
    ]
